### ISSUE TITLE
clash between available sectors and sectors

### ISSUE THREAD

**Issue by benjaminpope** [SimonJMurphy/tess-waldo#1]
Hi Simon, 

Quick question - getting a puzzling behaviour in a clash between available_sectors and sectors for Canopus.

Ben

```
tid = 255559489
wd = Waldo('TIC %d' % tid)
print(wd.available_sectors)
print(wd.sectors)
```

**Comment by SimonJMurphy** [comment]
Sectors lists the sectors where the star is on silicon, according to tess_stars2px.
Available_sectors lists those where light curves are available according to tesscut.
I'm getting:
```
sectors = [ 2  5  6  7  8 28 32 33 34 35]
available_sectors = [ 5  6  7  8 28 32 33 34 35 38]
```
The differences are sector 2 and sector 38.
As far as I can tell, the star was on-silicon for sector 2, but no light curve is available. So that tracks. I don't know why no light curve was made. Maybe because this star is super bright?
The strange thing is that sector 38 is showing as 'available' when there isn't currently a light curve, yet it's not shown as on-silicon for that sector. This is likely to do with the [currently incomplete ingestion of sector 38](https://outerspace.stsci.edu/display/TESS/TESS+Holdings+Available+by+MAST+Service).

Manual checking has shown that tess-waldo is performing as it should, based on data it is getting from those sources.
